### ISSUE TITLE
Call to undefined method App\Models\User::isSuper()

### ISSUE THREAD

**Issue by mikemartin** [aryehraber/statamic-impersonator#18]
When viewing the CP user listing on the latest Statamic version, the below error is thrown.

```
[2021-12-20 01:20:14] local.ERROR: Call to undefined method App\Models\User::isSuper() {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method App\\Models\\User::isSuper() at /Users/mike/Sites/depressionproject/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71)
[stacktrace]
#0 /Users/mike/Sites/depressionproject/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException('isSuper')
#1 /Users/mike/Sites/depressionproject/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2132): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'isSuper', Array)
#2 /Users/mike/Sites/depressionproject/vendor/aryehraber/statamic-impersonator/src/ImpersonatorAction.php(20): Illuminate\\Database\\Eloquent\\Model->__call('isSuper', Array)
#3 /Users/mike/Sites/depressionproject/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): AryehRaber\\Impersonator\\ImpersonatorAction->visibleTo(Object(Statamic\\Auth\\Eloquent\\User))
#4 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(AryehRaber\\Impersonator\\ImpersonatorAction), 7)
#5 /Users/mike/Sites/depressionproject/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter(Array, Object(Closure), 1)
#6 /Users/mike/Sites/depressionproject/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(358): Illuminate\\Support\\Arr::where(Array, Object(Closure))
#7 /Users/mike/Sites/depressionproject/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->filter(Object(Closure))
#8 /Users/mike/Sites/depressionproject/vendor/statamic/cms/src/Actions/ActionRepository.php(27): Illuminate\\Support\\HigherOrderCollectionProxy->__call('visibleTo', Array)
#9 /Users/mike/Sites/depressionproject/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Actions\\ActionRepository->for(Object(Statamic\\Auth\\Eloquent\\User))
```

Support details:
```
Statamic 3.2.27 Pro
Laravel 8.76.2
PHP 8.0.13
aryehraber/statamic-impersonator 2.3.1
doublethreedigital/duplicator 2.0.1
doublethreedigital/runway 1.1.0
goldnead/statamic-toc 1.0.9
mikemartin/helpscout-beacon 1.0.2
mikemartin/samcart 1.0.8
statamic/seo-pro 2.3.2
```

**Comment by aryehraber** [comment]
Hey @mikemartin, thanks for bringing this to my attention.

Looks like a recent feature to stop non-Super Admins impersonating Super Admins has broken something... Will try and look into it ASAP!

**Comment by mikemartin** [comment]
Hey @aryehraber,
It may be similar to this fix here:

https://github.com/doublethreedigital/runway/commit/3692195990a2fd1a0fae57e58a4099445b43a385

**Comment by aryehraber** [comment]
Oh nice, this looks promising! Thanks!

**Comment by aryehraber** [comment]
Just tagged v2.4.0 -- please give it a run and report back if it works now 🤞

**Comment by mikemartin** [comment]
Hey @aryehraber,

I'm not longer getting an error but Impersonating does not seem to work anymore. I've reported the issue here:
https://github.com/aryehraber/statamic-impersonator/issues/20

**Comment by aryehraber** [comment]
Should be ok now, please check again when you have a moment.

**Comment by aryehraber** [comment]
Closing this one up since it should have been fixed in latest version, please re-open if you are still encountering this issue!
